INSERT INTO Employee_Position(Name,EP_Status) VALUES ('IT - Officer',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('President',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('General Manager',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Compliance Officer',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Chief Accountant',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Chief Internal Auditor',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Accounting Assistant',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Accounting Clerk',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Senior Auditor',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Internal Auditor',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Legal Officer',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Executive Assistant',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Executive Clerk',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('HR Officer',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('ROPA Manager/Appraiser',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Chiel Loan Officer',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Liaison Employee/CI Appraiser',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Inward Processor',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('IT Staff',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Company Driver',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Branch Manager',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Officer-In-Charge',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Cashier',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Teller',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Bookkeeper',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Loan Officer',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Loans Clerk',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Project Officer',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Janitor/Messenger',1);
INSERT INTO Employee_Position(Name,EP_Status) VALUES ('Trainee',1);