CREATE TABLE [dbo].[SSSTable](
	[SSS_id] [int] IDENTITY(1,1) NOT NULL,
	[SSS_range1] [float] NOT NULL,
	[SSS_range2] [float] NOT NULL,
	[SSS_range3] [float] NOT NULL,
	[SSS_range4] [float] NOT NULL,
	[SSS_range5] [float] NOT NULL,
	[SSS_range6] [float] NOT NULL,
	[SSS_range7] [float] NOT NULL,
	[SSS_range8] [float] NOT NULL,
	[SSS_range9] [float] NOT NULL,
	[SSS_range10] [float] NOT NULL,
	[SSS_range11] [float] NOT NULL,
	[SSS_range12] [float] NOT NULL,
	[SSS_range13] [float] NOT NULL,
	[SSS_range14] [float] NOT NULL,
	[SSS_range15] [float] NOT NULL,
	[SSS_range16] [float] NOT NULL,
	[SSS_range17] [float] NOT NULL,
	[SSS_range18] [float] NOT NULL,
	[SSS_range19] [float] NOT NULL,
	[SSS_range20] [float] NOT NULL,
	[SSS_range21] [float] NOT NULL,
	[SSS_range22] [float] NOT NULL,
	[SSS_range23] [float] NOT NULL,
	[SSS_range24] [float] NOT NULL,
	[SSS_range25] [float] NOT NULL,
	[SSS_range26] [float] NOT NULL,
	[SSS_range27] [float] NOT NULL,
	[SSS_range28] [float] NOT NULL,
	[SSS_range29] [float] NOT NULL,
	[SSS_range30] [float] NOT NULL,
	[SSS_range31] [float] NOT NULL,
	[SSS_ER_range1] [float] NULL,
	[SSS_ER_range2] [float] NULL,
	[SSS_ER_range3] [float] NULL,
	[SSS_ER_range4] [float] NULL,
	[SSS_ER_range5] [float] NULL,
	[SSS_ER_range6] [float] NULL,
	[SSS_ER_range7] [float] NULL,
	[SSS_ER_range8] [float] NULL,
	[SSS_ER_range9] [float] NULL,
	[SSS_ER_range10] [float] NULL,
	[SSS_ER_range11] [float] NULL,
	[SSS_ER_range12] [float] NULL,
	[SSS_ER_range13] [float] NULL,
	[SSS_ER_range14] [float] NULL,
	[SSS_ER_range15] [float] NULL,
	[SSS_ER_range16] [float] NULL,
	[SSS_ER_range17] [float] NULL,
	[SSS_ER_range18] [float] NULL,
	[SSS_ER_range19] [float] NULL,
	[SSS_ER_range20] [float] NULL,
	[SSS_ER_range21] [float] NULL,
	[SSS_ER_range22] [float] NULL,
	[SSS_ER_range23] [float] NULL,
	[SSS_ER_range24] [float] NULL,
	[SSS_ER_range25] [float] NULL,
	[SSS_ER_range26] [float] NULL,
	[SSS_ER_range27] [float] NULL,
	[SSS_ER_range28] [float] NULL,
	[SSS_ER_range29] [float] NULL,
	[SSS_ER_range30] [float] NULL,
	[SSS_ER_range31] [float] NULL,
	[SSS_status] [varchar](100) NOT NULL DEFAULT ('ACTIVE'),
PRIMARY KEY CLUSTERED 
(
	[SSS_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

